---
kind: pipeline
type: docker
name: nginx-php-sidecar-stg

steps:
  - name: publish
    image: plugins/ecr
    settings:
      repo:  '541049731097.dkr.ecr.eu-west-1.amazonaws.com/nginx-sidecar'
      registry: 541049731097.dkr.ecr.eu-west-1.amazonaws.com 
      create_repository: true
      region: eu-west-1
      access_key:
        from_secret: access_key_stg
      secret_key:
        from_secret: secret_key_stg
      tags: 
        - latest 
        - ${DRONE_COMMIT_SHA}
    when:
      event: [tag,push]
      branch: [testing]

---
kind: secret
name: access_key_stg
get:
  path: stg/creds
  name: access_key

---
kind: secret
name: secret_key_stg
get:
  path: stg/creds
  name: secret_key

